### ISSUE TITLE
Parsing paths containing multiple slashes issues

### ISSUE THREAD

**Issue by veptechno** [just-ai/jaicf-kotlin#183]
Multiple slashes in reaction paths are interpreted as multiple states with empty names, but they are allowed and equivalent to a single slash in Unix systems. There are also problems with slashes in the names of states.
I think we should parse as in Unix systems and forbid slashes in the names of states (except for one leading slash in top-level states)

**Comment by nikvoloshin** [comment]
@veptechno is this issue resolved?
