### ISSUE TITLE
ActionErrorHook cannot prevent exception from throwing

### ISSUE THREAD

**Issue by Denire** [just-ai/jaicf-kotlin#49]
`ActionErrorHook` is a hook invoked on action error. But use case for this hook looks a bit unclear.

Having error, user might want to handle this error, but hook does not allow error handling. It only allows to react in some way to error, while further processing in `BotEngine` will be aborted.

@morfeusys maybe we should create `ActionErrorHandler` instead of `ActionErrorHook`?

**Comment by morfeusys** [comment]
@Denire maybe it's better to fix an implementation of BotEngine that should to work with this type of hook the same way as with others?
