### ISSUE TITLE
Develop Barge-in

### ISSUE THREAD

**Issue by srhxz** [just-ai/jaicf-kotlin#60]
Develop barge-in to make available routes from state by intents, or play some another replica

**Comment by Denire** [comment]
@srhxz You mean implementing something similar to [JAICP BargeIn]( https://help.just-ai.com/#/docs/en/telephony/bargein)?

Looks like we can implement similar things in `Scenario DSL` like:
```kotlin
action {
  reactions.telephony?.sayWithBargeIn("my reply", goOnInterrupt = "/some/handler/state")
}
```

**Comment by srhxz** [comment]
@Denire 
Yeah, or plus some trigger for user reaction, words count before activate Bargein

**Comment by Denire** [comment]
Smart barge-in dsl were introduced in #152 
Scheduled to release 1.0
