### ISSUE TITLE
Channel-specific scenarios

### ISSUE THREAD

**Issue by morfeusys** [just-ai/jaicf-kotlin#84]
Looks like it's common use-case when the user have to create dialogue scenario for only a single channel. In this case accessing a channel-specific interfaces like `reactions.alexa?` or  `request.alexa?` could be annoying.
As I think we could provide some channel-specific builders to make it possible to automatically cast `BotContext`'s interfaces to channel-specific and activator-specific implementations.

**Comment by nikvoloshin** [comment]
In addition, we can think about a similar thing for `ActivatorContext` in `ActionContext`, if the `activators` block has a single (or of a single type) activator.
